version: '3.7'

services:
  licenseserivce:
    image: licenseserivce:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
          aliases:
            - "licenseserivce"
networks:
  backend:
    driver: bridge